--Had to use website instead of url and information instead of desc.
--Pretty sure these are some kind of reserved keyword in PostgreSQL

drop table if exists bookmarks;
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  website text,
  information text,
  rating numeric
);
insert into bookmarks (title, website, information, rating)
values
('Google', 'https://www.google.com', 'Pretty popular', '2'),
('Yahoo', 'https://www.yahoo.com', 'Pretty old', '1'),
('Cat Pictures', 'https://www.catpics.com', 'Pictures of cats (hopefully)', '4'),
('Web Oasis', 'https://www.weboas.sis', '4 h4x0rs', '5'),
('Google Again', 'https://www.google.com', 'Pretty scary', '3'),
('Ask Jeeves', 'https://www.askjeeves.com', 'Alien technology from the future', '5'),
('Thinkful', 'https://www.thinkful.com', 'Learn Stuff', '4'),
('Dog Pictures', 'https://www.dogpics.com', 'Pictures of dogs (hopefully)', '5'),
('Distro Watch', 'https://www.distrowatch.com', 'Pick a real operating system', '5'),
('League of Legends', 'https://www.playlol.com', 'Most popular video game in the world', '5');